// Package graph mounts GraphQL endpoints.
// NOTE: gqlgen-generated files (generated.go, models_gen.go, *.resolvers.go)
// are produced by `make gen`. This file is the hand-written wrapper.
package graph

import (
	"net/http"

	"go.mongodb.org/mongo-driver/mongo"

	"github.com/sigma/server/internal/auth"
	"github.com/sigma/server/internal/db"
)

// Resolver is wired by the generated code (see resolver.go after `make gen`).
type Resolver struct {
	PG       *db.PG
	Mongo    *mongo.Client
	Verifier *auth.Verifier
}

// NewHandler returns the GraphQL HTTP handler.
// The actual implementation is generated by gqlgen; this stub avoids
// import errors until you run `make gen`.
func NewHandler(pg *db.PG, m *mongo.Client, v *auth.Verifier) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, "run `make gen` to generate the gqlgen handler", http.StatusNotImplemented)
	})
}

func NewPlayground(endpoint string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html")
		_, _ = w.Write([]byte(`<!doctype html><html><body>
<h2>GraphQL Playground</h2>
<p>Run <code>make gen</code> in <code>server/</code> to enable the gqlgen-generated playground at ` + endpoint + `.</p>
</body></html>`))
	})
}
